hostname: debian

username: apprunner
home_dir: /home/{{ username }}
user_password: changeme

ssh_public_key_file: id_rsa.pub

# If set to true, will perform an apt upgrade
allow_upgrade: false

# Packages to be installed
default_packages:
  - ufw
  - openssl
  - git
  - vim
  - curl
  - sudo
  - network-manager
  - unzip

# Default groups to be created and assigned to the user
default_groups:
  - "{{ username }}"
  - ssh
  - docker
  - sudo

timezone: Asia/Kolkata