- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: restarted

- name: Restart ssh
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: restarted

- name: Enable UFW
  community.general.ufw:
    state: enabled